version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./${DB_DIR}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  registry:
    image: ghcr.io/sunbird-rc/sunbird-rc-core:${RELEASE_VERSION}
    volumes:
      - ./${SCHEMA_DIR}:/home/sunbirdrc/config/public/_schemas
    environment:
      - connectionInfo_uri=jdbc:postgresql://${DB_URL}/${DB_NAME}
      - connectionInfo_username=${DB_USERNAME}
      - connectionInfo_password=${DB_PASSWORD}
      - authentication_enabled=false
      - claims_enabled=false
      - opa_enabled=false
      - search_limit=2000
      - search_providerName=${SEARCH_PROVIDER_NAME}
      - signature_enabled=true
      - sign_url=http://certificate-signer:8079/sign
      - verify_url=http://certificate-signer:8079/verify
      - sign_health_check_url=http://certificate-signer:8079/health
      - pdf_url=http://certificate-api:8078/api/v1/certificatePDF
      - certificate_health_check_url=http://certificate-api:8078/health
      - template_base_url=http://registry:8081/api/v1/templates/ #Looks for certificate templates for pdf copy of the signed certificate
      - registry_base_apis_enable=false
      - logging.level.root=INFO
      - certificate_enabled=true
      - encryption_enabled=false
      - enable_external_templates=true
      - async_enabled=${ASYNC_ENABLED}
      - kafka_bootstrap_address=${KAFKA_BOOTSTRAP_URL}
      - webhook_enabled=false
      - webhook_url=http://localhost:5001/api/v1/callback
      - manager_type=${MANAGER_TYPE}
      - swagger_enabled=true
      - swagger_title=Bangladesh Demo PoC
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -nv -t1 --spider http://localhost:8081/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 10
  keycloak:
    image: ghcr.io/sunbird-rc/sunbird-rc-keycloak:latest
    volumes:
      - ./${KEYCLOAK_IMPORT_DIR-imports}:/opt/jboss/keycloak/imports
    environment:
      - KEYCLOAK_LOGO=https://svgshare.com/i/hCs.svg
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER-admin}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD-admin}
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
      - PROXY_ADDRESS_FORWARDING=true
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9990/ || exit 1']
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - '8080:8080'
      - '9990:9990'
    depends_on:
      db:
        condition: service_healthy
  certificate-signer:
    image: ghcr.io/sunbird-rc/sunbird-rc-certificate-signer:${RELEASE_VERSION}
    environment:
      - PORT=8079
      - TIME_ZONE=${TIME_ZONE-Asia/Kolkata}
    ports:
      - "8079:8079"
    volumes:
      - ./imports/keys:/etc/signer
    healthcheck:
      test:
        [ "CMD-SHELL", "curl -f http://localhost:8079/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 10
  certificate-api:
    image: ghcr.io/sunbird-rc/sunbird-rc-certificate-api:${RELEASE_VERSION}
    environment:
      - PORT=8078
      - QR_TYPE=W3C-VC
    ports:
      - "8078:8078"
    healthcheck:
      test:
        [ "CMD-SHELL", "wget -nv -t1 --spider http://localhost:8078/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 10
  public-key-service:
    image: ghcr.io/sunbird-rc/sunbird-rc-public-key-service
    environment:
      - CONFIG_BASE_PATH=/etc/keys
    ports:
      - '3300:3300'
    healthcheck:
      test:
        ['CMD', 'curl', '-f', 'localhost:3300/public-key-service/api/v1/health']
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - ./imports/keys:/etc/keys
  context-proxy-service:
    image: ghcr.io/sunbird-rc/sunbird-rc-context-proxy-service
    ports:
      - '4400:4400'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'localhost:4400/health']
      interval: 30s
      timeout: 10s
      retries: 10
  # demo-ui: 
  #   image: sunbird-rc/bangladesh-demo-ui
  #   ports:
  #     - '81:80'
  #   volumes:
  #     - ./imports/nginx-configurations/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./imports/nginx-configurations/config.json:/usr/share/nginx/html/assets/config/config.json
  #   depends_on:
  #     registry:
  #       condition: service_healthy
  #     keycloak:
  #       condition: service_healthy
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    env_file:
#      - .env
#    volumes:
#      - ./imports/nginx/:/etc/nginx/conf.d/:ro